DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '÷˜º¸ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '–’√˚',
	age INT(11) NULL DEFAULT NULL COMMENT 'ƒÍ¡‰',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '” œ‰',
	PRIMARY KEY (id)
);
